### ISSUE TITLE
With audio enabled sounds of the live game also appear when looking at the archive

### ISSUE THREAD

**Issue by henrikarordina** [TCEC-Chess/tcecgui#107]

**Comment by henrikarordina** [comment]
So, with 2 tabs open (one live, one archive) I hear all the sounds twice.

**Comment by octopoulos** [comment]
![image](https://user-images.githubusercontent.com/7278312/92420339-14c1ce00-f173-11ea-8770-374110889f5f.png)

**Comment by henrikarordina** [comment]
This was out of misunderstanding what the option was for: I thought it was for stopping sounds of the archive itself when replaying a game with the 'play' button. I guess it was for stopping sounds of the live game while looking at the archive... thanks!
