### ISSUE TITLE
H2H tab broken (confirmed by others)

### ISSUE THREAD

**Issue by zer0000brain** [TCEC-Chess/tcecgui#109]
The head to head section lists the games with wrong index numbers and links incorrectly. 
It shows the correct games for the current matchup contentwise (example here: SF-Ethereal), but with wrong index numbers(6+13 instead of the correct 22+50) and clicking on them brings you to those wrong games (6+13 in this case, SF-Scorpio) instead of the actual head2head games (22+50 for SF-Ethereal).
![grafik](https://user-images.githubusercontent.com/32910807/92389664-cb916000-f119-11ea-83e7-80df51d6a469.png)

hope this helps :)

**Comment by zer0000brain** [comment]
also confirmed it in a readonly vm and with other users and different browsers, so its not a cache issue. and the results seem to be the exact same wrong games, so not random.

**Comment by octopoulos** [comment]
fixed in upcoming update
