### ISSUE TITLE
Archive H2H tab is erratic

### ISSUE THREAD

**Issue by henrikarordina** [TCEC-Chess/tcecgui#110]
The H2H tabs show incorrect numbers sometimes

for example

https://tcec-chess.com/#div=p&game=35&season=19

shows games 2, 9 and 16 (incorrect, not even showing 35 itself)

https://tcec-chess.com/#div=p&game=3&season=19

shows games 1, 8 and 15 (incorrect. not even showing 3 itself)

But sometimes it does work:

https://tcec-chess.com/#div=p&game=10&season=19

shows games 3 and 10 (correct)

I already tried F5, ctrl-F5, and clearing the cache.

**Comment by octopoulos** [comment]
fixed in upcoming update
