### ISSUE TITLE
Ability to have more than 3 main columns

### ISSUE THREAD

**Issue by Sopel97** [TCEC-Chess/tcecgui#127]
Forgive me if this is already possible, but I haven't found a way to have more than 3 columns for the main view (currently engine info, board, chat).

It would be nice to have an additional column in which we could for example put some graphs. There's a lot of empty horizontal space on wide screens.

**Comment by octopoulos** [comment]
How many columns maximum, like 5?

**Comment by Sopel97** [comment]
yea 5 should be enough even for extra wide monitors

**Comment by octopoulos** [comment]
Feature is coming soon.

**Comment by octopoulos** [comment]
Done. Need to change the 0 0 to something else, and then the column appears.
![image](https://user-images.githubusercontent.com/7278312/104829278-9092fc00-5872-11eb-9cd9-231976d0795c.png)
