### ISSUE TITLE
Eval TAB displaying eval of copied game instead of Live game

### ISSUE THREAD

**Issue by henrikarordina** [TCEC-Chess/tcecgui#128]
After copying archived game to PV(A) in Archive (by clicking the board, and pressing Ctrl-C) and switching to back Live, I expect, when moving the Table-PVA from PV(A) to Engine or PV, that the Eval graph (in Table-Eval) would display the kibitizing eval and eval of the Live game and not the copied game. However, to see the current game I have to switch to Archive again (and do nothing there) and then back to Live to see the Eval of the current game.

This is a workaround, but still: it's annoying to have to switch four times instead of twice. Also, I expect that the Eval graph should be shown when the PV(A) tab is active, but not with the PV or Engine tab active: then the eval (and kibitzing) of the Live game should be shown.

**Comment by octopoulos** [comment]
If you click on the Live board, the graph switches to Live graph, then if you click on the PVA board, it switches to PVA graph.
But yes, when PVA is inactive, then it should switch back to Live.

**Comment by octopoulos** [comment]
Fixed.
