### ISSUE TITLE
Use the FRC numbering scheme in the 'Opening' column when FRC events are being played

### ISSUE THREAD

**Issue by henrikarordina** [TCEC-Chess/tcecgui#130]
Use this? https://en.wikipedia.org/wiki/Fischer_random_chess_numbering_scheme

**Comment by octopoulos** [comment]
I had the idea to use this too.

**Comment by henrikarordina** [comment]
The numbers only show in the line at the top of the GUI (under 'Opening'), but not yet in the archive in the 'Games' Tab (it says 'Undefined' for everything).

Also, some openings (e.g. games 1 and 3 for S19 - FRC2 Semileague 1 show 'FRC #???'

**Comment by octopoulos** [comment]
Archive files are not related to the GUI. Someone can process the archive files to include the proper openings, even my code can be used for that purpose.
