### ISSUE TITLE
Link to chess960 analysis in lichess insted of standard one when playing FRC

### ISSUE THREAD

**Issue by moisesnb** [TCEC-Chess/tcecgui#132]
QOL when running FRC games: it's a little thing, but the link (right click) to lichess analysis could be for chess960 insted of standard. Just changes castling and opening book, but just in case it is a little change in code. Currently links to https://lichess.org/analysis/standard/ + FEN , FRC would be https://lichess.org/analysis/chess960/ + FEN

**Comment by octopoulos** [comment]
Done.
