### ISSUE TITLE
Copy FEN button only works correctly for move 0 in FRC (initial setup position)

### ISSUE THREAD

**Issue by henrikarordina** [TCEC-Chess/tcecgui#137]
When the Copy FEN button is used for an FRC game, it nicely makes it a real FRC FEN at move 0.

However, after one move it appears for me, after importing it in Arena that both the 'knowledge' that it's an FRC game is gone, and Arena thinks both sides are not allowed to castle.

I'm not an expert in FEN, so I can't really see what's wrong with the FEN itself, I can only describe what I see.

**Comment by octopoulos** [comment]
The FEN is correct. This is a problem with whatever software you're using. It needs to support SFEN (Shredder FEN), which is what 95% of the chess software and engines are using, maybe your software only supports X-FEN.
