### ISSUE TITLE
First time every day connecting to TCEC the complete kibitzers evals are not displaying

### ISSUE THREAD

**Issue by henrikarordina** [TCEC-Chess/tcecgui#138]
Workarounds:

switching to archive and then back to live
refresh the screen
close the tab and open the tab again
waiting one or two minutes until the kitbizing data is reloaded by the GUI

**Comment by henrikarordina** [comment]
The problem occurs with every odd numbered opening of a tab

first tab - problem, next tab - problem gone, next tab - problem back etc

**Comment by octopoulos** [comment]
Can you check if it's still a problem? version 20210106b

**Comment by henrikarordina** [comment]
Problem persists, but it different now. The 'reload page' work-around does no longer work; I have to switch to archive and then back to live to get the kibitzer data back in the graph.

**Comment by octopoulos** [comment]
Should be fixed in 20210118b
