### ISSUE TITLE
Play button changes back from pause symbol to play symbol after 2 ply replayed

### ISSUE THREAD

**Issue by henrikarordina** [TCEC-Chess/tcecgui#139]
To reproduce:

- go back to beginning of a game
- press Play, the game starts to play, the button changes to the Pause symbol
- notice that after 2 ply the button changes from Pause back to Play
- it does still work as if it is the Pause button

This can be repeated: press Play, (Pause changes to Play), press Play, working like Pause, etc.

The problem is present in both Live and Archive mode

**Comment by octopoulos** [comment]
Yeah, annoying phenomenon.
