### ISSUE TITLE
Less bellicose name of Event Stat Reverse kills

### ISSUE THREAD

**Issue by HansOveL** [TCEC-Chess/tcecgui#153]
Maybe I am too sensitive, but can we have a less aggressive name than Reverse kills in the Event stats. Maybe Double Wins or 2-0 openings?

**Comment by HansOveL** [comment]
Reverse Wins is another suggestion. Wins sounds less aggressive compared to kills, which is a word I don't like that much.

**Comment by octopoulos** [comment]
fixed in next version => Double wins
