### ISSUE TITLE
Spanish traductions after last introductions

### ISSUE THREAD

**Issue by moisesnb** [TCEC-Chess/tcecgui#170]
I detected some missed translations in table headers and in the info that show up when u point it whith mouse. I propose translations also.
- "Points" -> _**"Puntos"**_
- "points + direct encounters" and "[DE]"
             I propose translate "direct encounters" as "enfrentamientos directos" so proposed translations would be:
             -"points + direct encounters" -> **_"puntos + enfrentamientos directos"_**
             - "[DE]" -> _**"[ED]"**_

- "rMobility" and "r-Mobility score"
            If r-Mobility is an entity itself, that i think that can be, then i think it should be translated, but i prefer that Aloril or another decide that, if a translation is needed i think "r-Movilidad" or "Movilidad-r" are possible. Grammatically "Movilidad-r" made sense/its better but maybe that "broke" the "spirit" of r-Mobility. I propose to just translate score for the moment, and discuss the other term.
            - "r-Mobility score" -> "_**puntuación r-Mobility"**_
            - "rMobility" -> add the "-", **_"r-Mobility"_**
            Also in graphs it is shown "r-mobility" with M in lower case, not a problem at all but if the "trademark" of the term is wanted i think that the way to go is standarized the term.
           Searching a bit more i see different combinations of upper and lower cases used ("r-mobility", "R-Movility", "R-mobility") in https://wiki.chessdom.org/R-Mobility so all to you the prefered options of that.

- Boom options:
-"Boom options" -> **_"Opciones de boom"_**
-"Test" -> **_"Probar"_**
-"Consecutive" -> **_"Consecutivos"_**
-"Ply reset": i don't know how "ply" or the intention should be translated
-"Threshold" -> **_"Umbral"_**
-"shake" i suggest **_"temblor"_**
-"Sound boom" -> **_"Sonido de boom"_** or just **_"Sonido"_** as we are already in boom options
-"random" -> **_"aleatorio"_**
-"Reactivate" -> **_"Reactivar"_**
In general sound options: "Sound boom" -> **_"Sonido de boom"_**

- Current at spa.json: "average moves":"promedio de movidas" should be **_"promedio de movimientos"_**
            Checking the rest of the file all "moves" are translated as "movidas" should be _**"movimientos"**_ for all cases.
            In spanish we have "movimiento" and "jugada" both used in chess but i dont think what is best translation, for now **_"movimiento"_** and **_"movimientos"_** should be fine, but another opinions are welcome of course.
- Current at spa.json: "crash info":"info de fallas" should be **_"info de fallos"_**
            Same for "crash":"falla" and "crashes":"fallas" -> **_"fallo"_**, **_"fallos"_**
             I'm from Spain and I'm not software developer so for me "fallos" is fine, but maybe in latin america "fallas" is fine, and i dont know what word is used in developers enviroments
- Current at spa.json: "d/sd":"profundidad/selectiva" I guess to follow the spirit should be **_"p/ps"_**
- Current at spa.json: "3-Fold repetition":"Repetición de 3 veces" should be **_"Triple repetición"_**
- Current at spa.json: "aspect ratio":"aspecto de razón" should be **_"relación de aspecto"_**
- Current at spa.json: "audio options":"opciones de audio", should be **_"opciones de sonido"_**
- Current at spa.json: "audio set":"juego de sonidos" should be **_"conjunto de sonidos"_**
- Current at spa.json: "brown":"café" should be **_"marrón"_**
- Current at spa.json:"sound move":"sonido de pieza" should be **_"sonido de movimiento"_**
- Currently "stand" and "standings" are translated as "posiciones" in Spain we use _**"clasificación"**_ (or **_"Clasificación"_** according to format needed)
- Currently "wrap" are translated as "envolver", Excel for the same option use "ajustar texto", i suggest:
                -"wrap":"envolver" as **_"ajustar texto"_**
                -"wrap cross":"envolver cruces" as **_"ajustar cruces"_**
                -"wrap h2h":"envolver cara a cara" as **_"ajustar cara a cara"_**
                -"wrap sched":"envolver horario" as **_"ajustar horario"_**
                -"wrap stand":"envolver posiciones"  as **_"ajustar clasificación"_**
                - function of this option: https://i.imgur.com/RMBM7Gw.png
- Current at spa.json: "H2H":"cara a cara" for format purpose as header of the column i think that should be **_"Cara a cara"_**
- Current at spa.json: "[TCEC] is a computer chess tournament organized and maintained by Chessdom in cooperation with Chessdom Arena.":"[TCEC] es una competencia de ajedrez por computadora organizada y mantenida por Chessdom, en cooperación con Chessdom Arena." should change "competencia" for **_"competición"_**, also i would eliminate the comma.
- Current at spa.json: "wheel adjust":"adjustar rueda del mouse" ->"adjustar rueda del ratón"

- In game options: "threads" -> **_"hilos"_**
- Current at spa.json: "reset options":"reponer opciones" and "reset":"reponer" -> **_"restablecer opciones"_** and **_"restablecer"_** ("Restablecer" in red form for the last element in options menu)

Don't know how to translate but not sure about current translations:

- "grid copy":"grilla copia", "grid live":"grilla en vivo", "grid pv":"grilla vp", "grid pva":"grilla vpa", "grid":"grilla"
- "base border":"borde de tallo", "base color":"color de tallo", "base mix":"mezcla de tallo", "base size":"tamaño de tallo"
- "Puntaje(Elo)"
- "Quick every"
- "Wasm"

**Comment by octopoulos** [comment]
Thanks. I'll make the changes.
Wasm should remain "wasm".
Quick every = how fast to play moves when they're received at the same time, for ex. in some end games.

**Comment by moisesnb** [comment]
You are right with "sonido de pieza"!
Checking quick every I just realized that some options have explanations when u put the mouse over it (quick every is an example). I wish i have time to translate that too but I don't :( 
I don't know how to translate quick every with few words that is self-explanatory, it comes to me "tiempo minimo entre movimientos" maybe "tiempo minimo entre mov"
Again, thanks for your work!

**Comment by octopoulos** [comment]
By the way, boom is now divided into "boom" and "explosion", so the terms have changed to these:
boom increase
boom multiplier
boom ply reset
boom scale
boom visual
boom volume
boom test
explosion consecutive
explosion ply reset
explosion threshold
explosion visual
explosion volume
explosion sound
explosion test

There aren't many explanations in total. It doesn't matter if you translate them or not, some day, someone else will contribute.
That "quick every" would be difficult to translate. Even in English, it doesn't make sense, but it's the variable name I'm using in the code.

**Comment by moisesnb** [comment]
I prefer testing the functions before suggesting a wrong translation but is suggest:
-boom
boom increase
boom multiplier
boom ply reset
boom scaling
boom visual -> "opciones visuales de boom"
boom volume -> "volumen de boom" or just "volumen"
boom test ->"probar boom" or "prueba"
-explosion ->"explosión"
explosion consecutive
explosion ply reset
explosion threshold -> "umbral de explosión"
explosion visual -> "opciones visuales de boom"
explosion volume -> "volumen de explosión" or "volumen"
explosion sound -> "sonido de explosión" or "sonido"
explosion test -> "probar explosión" or "prueba"

Feel free to use it or not or use others, as said I will test it and give feedback when I understand the functions.
