### ISSUE TITLE
Super minor issue: selecting JOIN NEXT in a tab doesn't toggle its own active/inactive mode indication

### ISSUE THREAD

**Issue by henrikarordina** [TCEC-Chess/tcecgui#172]
This is very minor, but it stumped me for a minute; if you select the last tab in a set, it is obviously not joined with the next tab, because it _is_ the last one. So, now right-click, select JOIN NEXT, and it will join the next tab. So it works fine. However, it doesn't not immediately change its own status background colour, so if you're not paying full attention, it looks like clicking it failed.

**Comment by octopoulos** [comment]
Drag and drop has some bugs too. Haven't touched the code in months, and some updates I did elsewhere broke part of that code.

**Comment by octopoulos** [comment]
Anyway, fixed. Will be in the next update.
