### ISSUE TITLE
Suggestion: show common PV length as a number (in number of ply)

### ISSUE THREAD

**Issue by mooskagh** [TCEC-Chess/tcecgui#183]
What subject says: currently it's possible to see the diverging position in PV boards, or look at PV move list and estimate length of shared PV.

But it seems that what I'm interested in the most of the time is whether common PV part is long or short, not what are particular positions at diversion point.

**Comment by octopoulos** [comment]
Sounds like a good idea

**Comment by octopoulos** [comment]
Feature is coming soon.
