### ISSUE TITLE
Eval graph and related graphs not showing for Archive games

### ISSUE THREAD

**Issue by bjbraams** [TCEC-Chess/tcecgui#19]
New gui since 20120-05-14. I go to Archive and open a game and flip through the moves. The Eval graph and its neighbors (Time, Speed, Nodes, Depth, TB) remain blank throughout. Sometimes, after a long time (minutes) the graphs appear. Sometimes they never appear.

**Comment by Aloril** [comment]
Several GUI updates since: works now.
