### ISSUE TITLE
In mobile (narrow) layout, thinking animation is shown for wrong player when the board is flipped

### ISSUE THREAD

**Issue by mooskagh** [TCEC-Chess/tcecgui#213]
See screenshot:

![image](https://user-images.githubusercontent.com/11266455/105675311-38e73700-5ee9-11eb-9e86-17b057a85968.png)

Steps to reproduce:
1. Open TCEC website.
2. Shrink the browser window (or open it on a smartphone)
3. Flip the board so that black pieces are shown in the bottom
4. Note the thinking animation is shown for wrong player.

![Peek 2021-01-25 08-46](https://user-images.githubusercontent.com/11266455/105675802-e8240e00-5ee9-11eb-925f-1751ed8e0a06.gif)

UPD: It seems that it normalizes after the move is made, so it's not a very severe bug.

**Comment by octopoulos** [comment]
You're right. I forgot to flip the clock too. I'll have a look later.
By the way, your last suggestion was very good, about the ply agreement.
