### ISSUE TITLE
Small locks are closed and red when coming back from archive

### ISSUE THREAD

**Issue by snicolet** [TCEC-Chess/tcecgui#218]
Steps to reproduce:

1. Click on Schedule.
2. Open one of the finished games of the sufi, for instance https://tcec-chess.com/#div=sf&game=70&season=20 . This correctly opens the finished game in the archive mode.
3. Browse the game to replay some moves of that finished game: locks under PV boards are blue and closed, which seems OK.
4. Click on Live at the top left of the screen to come back to the current live game

==> the small locks are closed and red.

**Comment by snicolet** [comment]
IMO it is probably OK to always unlock the small locks when clicking on Live, whatever their state was when entering Archive mode.

**Comment by octopoulos** [comment]
Yeah I just tried and you're right, the locks are red.
I'll implement your idea of unlocking the locks whenever clicking on "Live".

**Comment by snicolet** [comment]
@octopoulos 
I have tried it a bit and it seems better, thanks :-)
