### ISSUE TITLE
My issues with the website here

### ISSUE THREAD

**Issue by AndrewTCEC** [TCEC-Chess/tcecgui#222]
1. Firefox Mobile support is broken for the boards.
2. When the page is translated, the writings below the graphs don't without reloading the page.
I may add more issues once I will notice them.

**Comment by AndrewTCEC** [comment]
![Screenshot_20210130_015344_org mozilla firefox](https://user-images.githubusercontent.com/77082125/106335762-7dceed00-629e-11eb-8d74-eab63c54a89c.jpg)

**Comment by AndrewTCEC** [comment]
Rus locale
![Screenshot_20210130_112357_com android chrome](https://user-images.githubusercontent.com/77082125/106351498-b4802400-62ed-11eb-8292-4351a3b12ed9.jpg)
Eng locale
![Screenshot_20210130_112345_com android chrome](https://user-images.githubusercontent.com/77082125/106351500-b5b15100-62ed-11eb-8590-2aa508280da4.jpg)

**Comment by octopoulos** [comment]
#2 => reload the page = fixed

**Comment by AndrewTCEC** [comment]
> #2 => reload the page = fixed

Yes, I know, @octopoulos, but I would like for it to be translated without reloading the page.

**Comment by AndrewTCEC** [comment]
#2 Problem can be ignored, #1 problem is still present. Might be an issue with Firefox itself though.
