### ISSUE TITLE
Add the three missing Opening Outcomes to Event Stats

### ISSUE THREAD

**Issue by HansOveL** [TCEC-Chess/tcecgui#225]
At the moment we have 1 out 4 possible Openings outcomes in the Event stats:

0. Double Wins
Also known as Reverse kills. Could consider reverting the name back to Reverse kills as this is mostly used in chat. 
One engine win both games.
Opening result is 2-0.

The following three Opening outcomes are missing:

1. Win+draw
One engine wins the opening by winning one game and drawing the other. 
Opening result is 1.5-0.5.

2. Double draw
Both games end in draws.
Opening result is 1-1.

3. Win+Loss
Each engine wins one game and loses the other game.
This is a potentially busted opening. It could instead be named: Busted?
Opening result is 1-1.

**Comment by octopoulos** [comment]
Done, version 20210220
