### ISSUE TITLE
The disagreement sign @ for black PV is not seen when the black's PV look is set at any move other than a disagreement one (For a 'PV' window)

### ISSUE THREAD

**Issue by AndrewTCEC** [TCEC-Chess/tcecgui#236]
![image](https://user-images.githubusercontent.com/77082125/109347610-79d5c100-7884-11eb-89f9-5bbcd062044b.png)
![image](https://user-images.githubusercontent.com/77082125/109347126-b228cf80-7883-11eb-8909-10fd59b6d5c2.png)
Look at black PV in 'PV' window. It is barely seen/gone on the first image! And when B's PV is set on a disagreement move (image 2), it is perfectly fine! It doesn't bother me, but some other people, and can you fix it?

**Comment by octopoulos** [comment]
Next time, try to make the title shorter, like "Diagreement sign @ for black PV is barely visible".
Anyway, fixed, but I don't know when we'll merge that, it's better to wait for more changes.

**Comment by AndrewTCEC** [comment]
Okay, that works for me too.
