### ISSUE TITLE
Selecting a custom language json file sets the language the french

### ISSUE THREAD

**Issue by HelixPiano** [TCEC-Chess/tcecgui#238]
Basically the title.
When you click "..." to load a custom json file it will set the language automatically to french, even before you've selected any file.

**Comment by octopoulos** [comment]
It's on purpose, not a bug. That only happens if you had English selected. Try with another language and then `...`
It doesn't actually set the language to French, it just does this so you can select `...` again.

**Comment by HelixPiano** [comment]
Ah ok. I found the problem. 
My json file had an error and so it didn't load but instead defaulted back to the selected language.

**Comment by octopoulos** [comment]
Ah I see.
Anyway, this feature `...` is quite useful indeed!
