### ISSUE TITLE
Display Game Number

### ISSUE THREAD

**Issue by HansOveL** [TCEC-Chess/tcecgui#242]
Displaying the Game Number in the main part of the page would provide useful information, for example if you want to set up a bet like 'Outcome of game 17'. Now we need to check the game number in the Schedule tab as only the Round is displayed in the main window. We now see something like Round 9.1 for game number 17 for example.

The Header could be Game# like in the Schedule tab.

Maybe could even display how many game there are, such as: 17 of 24 (instead of just 17), which would be informative when people log on for the first time for an event.

**Comment by octopoulos** [comment]
Like this?
![image](https://user-images.githubusercontent.com/7278312/110221270-951b7e80-7ecb-11eb-92bf-715dbf3ea309.png)

**Comment by HansOveL** [comment]
That looks great!
