### ISSUE TITLE
Safari iPad4 not working

### ISSUE THREAD

**Issue by MelleKoning** [TCEC-Chess/tcecgui#27]
The new tcec gui does not render on iPad4 safari.
Also tried the chrome app.
Also tried both desktop view and mobile view.

What is the best alternative or backup gui for an iPad4?

**Comment by Aloril** [comment]
Old GUI is at https://tcec-chess.com/liveold.html

**Comment by octopoulos** [comment]
Unfortunately, I don't have an iPad4, otherwise I would be able to debug and fix the problem.

**Comment by norabor** [comment]
The buttons above the eval-window, the graphs-window and the chat-window dont work on ipad. Any browser. Safari, edge, firefox. All the rest seems to work fine. Ipados 13.5. I dont think it is limited to old ipad 4. I have the new big ipad pro.

**Comment by norabor** [comment]
For me its working now. Thanks.

**Comment by MelleKoning** [comment]
Thanks, the liveold.html works for the ipad here. Please keep it alive :-)

**Comment by octopoulos** [comment]
Should be working now (version 20200702) because I made it work on iPhone.
