### ISSUE TITLE
MS Edge, Win 10, few glitches

### ISSUE THREAD

**Issue by DragonMist** [TCEC-Chess/tcecgui#28]
1. every game notation (below the main board) starts with zeroeth, empty move. I. e.
"0. 1. c4 e6 2. d4 Nf6 etc."
2. after standby (laptop screen shut and reopen) game notation does not show the whole game, but only last few lines, i.e. can not be scrolled back to the beginning.
3. after standby (laptop screen shut and reopen) white and black horizontal bars below and above the main board, that were visible on PV tab view, disappear*
4. White and black horizontal bars disappear with every new game (*one needs to go to Engine info tab, than back to PV tab to get them back)
Thanks.
Edit:
5. after refresh (F5) the page does not remember the vertical scroll position

**Comment by octopoulos** [comment]
1. zero was introduced in order to go to the initial position, if you check the old site, it's not possible. It's not a glitch, but could be renamed and skipped when you do "copy moves".
2. ok, it's not a glitch but a missing feature, the server is not sending a history of the moves until a refresh is performed and the GUI cannot detect a standby ... it's possible to detect that moves are missing and trigger a refresh, but that must be done very carefully, as it could request too many updates.
3 + 4: maybe the new version has fixed those issues, at least I can't reproduce these errors.
5: I cannot reproduce this problem, the vertical scroll position is always remembered, on Edge Version 83.0.478.37 (Official build) (64-bit) + Win10 + Surface pro 7.

**Comment by DragonMist** [comment]
Thank you both for addressing these and for updated GUI @octopoulos and sorry for calling all these glitches, what do I know.

Looks like 3, 4 and 5 are fixed, but I need to report 2 more:

a) MS Edge hovering over kings above engine avatars shows nothing (used to be egine parametars info)
b) MS Edge can not select (and therefore copy) anything on the screen, not game moves not chat.

**Comment by octopoulos** [comment]
Hi, you're welcome!
Going to check a) with Edge.
b => try to disable "extra => drag and drop"

**Comment by DragonMist** [comment]
a) Whoa, my Edge shows version 44.18362.449.0 but I was under impression it keeps updating itself continuously ... Win 10 x64, Asus ZenBook - perhaps try to manualy update Edge? ...
b) did not help

**Comment by DragonMist** [comment]
> a) Whoa, my Edge shows version 44.18362.449.0 but I was under impression it keeps updating itself continuously ... Win 10 x64, Asus ZenBook - perhaps try to manualy update Edge? ...
> b) did not help

Ok, my whole system, Windows and everything, is on Croatian, and my Edge doesn't even allow for manual update - missing that feature (and some others I've noticed). Better not waste your time any more with that.

**Comment by DragonMist** [comment]
> > a) Whoa, my Edge shows version 44.18362.449.0 but I was under impression it keeps updating itself continuously ... Win 10 x64, Asus ZenBook - perhaps try to manualy update Edge? ...
> > b) did not help
> 
> Ok, my whole system, Windows and everything, is on Croatian, and my Edge doesn't even allow for manual update - missing that feature (and some others I've noticed). Better not waste your time any more with that.

Yeah, seems like my Edge did not update for ages ... updated it maually and now no problems at all. Thankyou!

**Comment by octopoulos** [comment]
Haha, I also had version 44 until I decided to manually update.
Keep sending more bug reports or feature requests, I can't guarantee to fix everything, but at least some % of them. For example the standby feature will be implemented at some point.

**Comment by DragonMist** [comment]
Ok, and thanks once again. From what I see now, only 2 things left:
1. white and black info bars go missing from time to time still, even if I switch to some other application (?!) and return
2. sound - no matter what I do, I only get a) applause at the end of the game, and b) first move after I change any setting on Audio there is. Tried everything, volume, Audio moves to All and back, switch off and on ... no use. Always I hear the very next move, and after that silence.

**Comment by octopoulos** [comment]
1. strange, but you can lock it on then? board => status => on, instead of auto.
2. yeah this is strange and I can't find a way to reproduce this phenomenon, but I know there's no sound on iPhone SE for example.

**Comment by DragonMist** [comment]
Hi @octopoulos there seems to be a problem with white and black horizontal bars (main board), they now show only engine name and eval, not the total time left and move time.
Also, Schedule tab above chat shows nothing.
While I'm at it, still vertical position of the page is not remembered after refresh.
Thanks.

**Comment by octopoulos** [comment]
Fixed schedule tab.
Other problems = I can't reproduce them.
