### ISSUE TITLE
Minimal mode

### ISSUE THREAD

**Issue by xoto10** [TCEC-Chess/tcecgui#47]
I tried creating a minimal layout with just the board (with status) and all the other stuff hidden. It looks right, but still uses a lot of cpu on my old laptop causing the fan to speed up (noisy).

Can we include a minimal layout in the list of preset options, and if possible, improve it over time to use less cpu (turn all live and chat off, just update moves and evals when moves are made)? Maybe leave the twitch video visible so we can confirm it is paused / pause it manually if necessary.

**Comment by octopoulos** [comment]
Hi, very good idea. The cpu utilization can be improved slightly if I transform some of the code to WASM. There might be a few other tweaks.
You can add your preset => preset folder.

**Comment by octopoulos** [comment]
Note: the chat is using most of the CPU, so if you want your laptop to remain quiet and cool, turn off the twitch chat, and twitch channel too.

**Comment by xoto10** [comment]
Ah, ok. I had kind of guessed that, but didn't have the tools to check for sure. (I think there used to be a "top" display in firefox to show which tabs / add-ons were using cpu but I didn't find it when I looked. Or was that in Chrome?)
I usually want the chat open, e.g. for tips on what the engines are doing right / wrong, but thanks, that's a useful point to remember when it's the game I really want to see rather than the chat. :)

**Comment by octopoulos** [comment]
I didn't really measure it, but my laptop was also getting hot and noisy, and I saw cpu utilization was high sometimes, turned off chat and went down to zero almost, and the laptop almost directly went silent. I repeated this process multiple times.
There's a minimal preset, by the way, but it's very minimal.
+ The problem with the chat taking all those resources is that it doesn't make sense to optimize the code anymore, as I mentioned earlier, I mean it's good to make it faster (which means less CPU intensive too), but it won't have a big impact anymore.

**Comment by xoto10** [comment]
Hmmm, I closed this and than looked at Task Manager in Firefox, probably the wrong order to do things in ! :)

Investigating a bit more, it seems that firefox uses more cpu when the TCEC (or twitch popout chat) is the displayed tab in a window. If I switch to a simple static page (github, blank, etc) in a different tab then cpu use drops away. Comparing TCEC (with chat hidden) to the twitch popout, I see about 25% use by TCEC page, and about 10% from twitch. The 10% leaves the fan on a lowish setting, the 25% cranks it up. It looks like googleads is the most consistent user, so I guess there's not much you can do about that. At least I found out that I can ease things by just choosing different tabs, so I don't have to close them and then reopen :)

![TCEC_twitch_cpu](https://user-images.githubusercontent.com/23479932/84635003-84b11700-aeea-11ea-9f52-6c0298af90cd.png)

**Comment by octopoulos** [comment]
I see player.twitch.tv too, try to close it.
Wow it's crazy that ads use that much power.

**Comment by xoto10** [comment]
Yeah, the twitch player uses some power for me (I normally pause the vid, obv uses a lot if I don't pause it) even if I close it, but it's less than the googleads thing.
I'll close this now, at least I can workaround by bringing a different tab to the front, and we've noted that googleads seems to be the main culprit - not much we can do about that.
