### ISSUE TITLE
on Android tablet clicking on the right arrow advances position by 2 moves

### ISSUE THREAD

**Issue by mike-rosen** [TCEC-Chess/tcecgui#62]
when interactively navigating the pgn on an active game or from archive, clicking the right arrow below the diagram advances the position by 2 moves not one.  it happens in chrome and firefox - but only on Android tablet (and phone?) but not on desktop.

**Comment by octopoulos** [comment]
Happens on desktop too, if you have a touch screen.

**Comment by octopoulos** [comment]
fixed
