### ISSUE TITLE
Board is not responsive thus does not fit

### ISSUE THREAD

**Issue by summersonnn** [TCEC-Chess/tcecgui#64]
As far as I know the board is not responsive. Sorry if there is an option that I'm not aware of for scaling it.
In my 1360x768 resolution laptop, I can't see the entire board at once.
![Adsız](https://user-images.githubusercontent.com/31991669/84392177-a8324400-ac02-11ea-81e1-620165b42adb.png)

**Comment by octopoulos** [comment]
Board is responsive, but it does so within the limits that you set in the options, check panel options min and max values.
