### ISSUE TITLE
Show actual eval instead of "10" when hovering mouse over the eval graph

### ISSUE THREAD

**Issue by astraujums** [TCEC-Chess/tcecgui#65]
When the actual eval is over 10 or under -10, the eval graph is capped at that value. When hovering the mouse over the corresponding eval value, the floating information box could show the real eval instead of "10" or "-10". In the situation in the attached image, the information box could be showing "250" instead of "10" for black (and whatever values were actually there at the time for blue and red).
![Real_eval](https://user-images.githubusercontent.com/6146363/84393637-80dc7680-ac04-11ea-8c94-de8c55f5adae.png)

**Comment by octopoulos** [comment]
Good catch, thanks, will fix this.

**Comment by octopoulos** [comment]
Fixed.

**Comment by Aloril** [comment]
Very nice.
