### ISSUE TITLE
Wrong color of figurines in the material difference display

### ISSUE THREAD

**Issue by PermanentBrain** [TCEC-Chess/tcecgui#67]
In Chrome 83.0.4103.97 / Windows 10 x64, the figurines in the material difference display have the wrong color. For example if Black is up a knight, a white knight is shown under the info for the black engine. It was always ok IOW reversed, up to just recently. Reloading, resetting and cookie deletion did not fix it.

According to a chat reply this may depend on the individual system, e.g. if on mobile phone or on a laptop. I think it could depend on the browser type or -version.

Thanks!

**Comment by octopoulos** [comment]
It's not a bug, it shows the captured pieces, so if you take a black Queen with your bishop, a black Queen appears, like in real life, instead of a second White queen.
However, I added a toggle option.
