### ISSUE TITLE
Highlight current location on eval graph

### ISSUE THREAD

**Issue by nickolasreynolds** [TCEC-Chess/tcecgui#71]
It would be nice if you could highlight the current location on the eval graph, for example by highlighting the active node, or drawing a vertical line, etc.

**Comment by octopoulos** [comment]
Idea is good and I had the same idea, and someone else too, unfortunately I'm currently using chartjs library for the graph, and until I get rid of it completely, then this feature can't be implemented. Once it's gone, then it's a piece of cake!

**Comment by octopoulos** [comment]
Done.
