### ISSUE TITLE
Blue kibitzer evals erroneously stored with wrong sign

### ISSUE THREAD

**Issue by nickolasreynolds** [TCEC-Chess/tcecgui#77]
The blue eval initially looks normal, but as I scroll through a game this starts happening: [https://i.imgur.com/EdAJSPr.png](https://i.imgur.com/EdAJSPr.png)

Half of the blue kibitzer evals (either all the whites, or all the blacks, I can't really tell which move the blue kibitzer is actually on) erroneously have their signs flipped when they're sent to permanent storage, which then shows up if you recall those evals by scrolling through the game.

**Comment by octopoulos** [comment]
Fixed.
