### ISSUE TITLE
Promotion animation wrongly moves piece to promotion square

### ISSUE THREAD

**Issue by robertnurnberg** [TCEC-Chess/tcecgui#78]
An example is

https://tcec-chess.com/#div=sf&game=18&season=18

If you replay the game, on move 49. a8=Q+, the queen comes flying from h6, where the white queen was captured on move 31.

**Comment by Alayan-stk-2** [comment]
Noticed the same issue

**Comment by octopoulos** [comment]
You have to imagine that the killed was killed and buried on h6, and then resurrects when the pawn goes to a8, that's why it flies from h6 to a8 :D

**Comment by robertnurnberg** [comment]
Unfortunately, the behaviour is not consistent. If you play through the moves in a different order, that flying does not happen. As far as I am concerned, the queen (or any other promotion piece) should just appear in place of the pawn.

**Comment by octopoulos** [comment]
fixed in upcoming update
