### ISSUE TITLE
Give an option so that 0 eval is always in the eval graph

### ISSUE THREAD

**Issue by Alayan-stk-2** [TCEC-Chess/tcecgui#80]
There is a clamp limit for max eval, but eval is between the min and max eval reached in the game (rounded down and up to 0.1). In a game where there never is an eval close to 0, this can make middle to high eval look quite low because the graph will only start at 0.3, 0.4, 0.5...

An option so that 0.00 is always in the displayed interval of the eval graph would be appreciated.

**Comment by octopoulos** [comment]
Good idea, but I think it should always be like that, so, not an option.

**Comment by octopoulos** [comment]
![image](https://user-images.githubusercontent.com/7278312/86504656-83715c80-bdbb-11ea-83de-582f046cea09.png)

**Comment by Alayan-stk-2** [comment]
> Good idea, but I think it should always be like that, so, not an option.

Works for me
