### ISSUE TITLE
Taking the unmoved rook doesn't change the castling rights in FEN

### ISSUE THREAD

**Issue by MoKy1978** [TCEC-Chess/tcecgui#90]
[https://tcec-chess.com/#div=nnueg&game=7&season=18](url)

FEN after move 14. bxa8=Q gxh1=Q is showing that all 4 castlings are still possible:
1bqk2r/5ppp/3b1n2/p2p4/8/P1P1P3/1B1N1P1P/R2QKB1q w KQkq - 0 15

And after move 25. O-O-O wR reappears on h1.

**Comment by octopoulos** [comment]
Yeah I see. Thanks.

**Comment by octopoulos** [comment]
Fixed, just had to rename a `from` to `to`
