### ISSUE TITLE
Please allow custom background color for page.

### ISSUE THREAD

**Issue by Khagrin2** [TCEC-Chess/tcecgui#92]
It would be very nice to allow user to set the "body" style element's background color.  I find myself doing this via browser's inspector tool currently.

**Comment by octopoulos** [comment]
Could be a color or an image even.

**Comment by Khagrin2** [comment]
If you try out some different colors via inspector you will see that, as is, using a background image would likely not be very pleasing.  Also note that the transparency setting on the "info box" (i.e. panel that has the eval, engine logos etc.) makes things a bit "iffy" when changing the background.  Similarly, changing the background effects the appearance of all of the tables ( i.e.  "standings", "crosstable", etc.).  Perhaps the backgrounds on those panels could also be made customizable.  Anyway, this is simply an enhancement request so not really high priority ... just something to mull over eh?  That said, changing the background, if easy to do, does allow for some nice looking tweaks!

**Comment by octopoulos** [comment]
Yeah, not so good, but I can add background element that has the background, and that element can have an opacity, that way, the background can be transparent, and then it can still look nice.

**Comment by octopoulos** [comment]
![image](https://user-images.githubusercontent.com/7278312/87722943-46dd3200-c7b9-11ea-89d3-a04c89229d66.png)

**Comment by Khagrin2** [comment]
Oooo.... That's pretty sweet :)   I can imagine there will be some pretty fine possibilities! Yes indeed!

**Comment by octopoulos** [comment]
Dark archive, same image:
![image](https://user-images.githubusercontent.com/7278312/87729997-ece36900-c7c6-11ea-9783-968f97780b6c.png)

**Comment by octopoulos** [comment]
Yeah, so you can:
- choose the background color
- choose a background image (in which case, the color is ignored, but the theme color is still used)
- choose the background opacity

Limitation: the image is only in memory, so, whenever you load the site, it disappears, you need to choose it again from your computer. But the color + opacity options remain.

**Comment by kanchess** [comment]
closed
